import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { 
  ClipboardCheck, 
  Download, 
  FileCheck, 
  AlertTriangle, 
  CheckCircle2,
  Utensils,
  Factory,
  Globe
} from "lucide-react";
import { cn } from "@/lib/utils";

interface ComplianceData {
  isComplianceReady: boolean;
  foodGradeRisk: "low" | "medium" | "high" | "not-applicable";
  industrialGradeSuitability: "suitable" | "conditional" | "not-suitable";
  exportComplianceReadiness: "ready" | "pending" | "not-ready";
  summary: string;
  documents: {
    name: string;
    available: boolean;
    type: "report" | "certificate";
  }[];
}

interface CompliancePanelProps {
  compliance: ComplianceData;
  className?: string;
}

const getRiskBadge = (risk: string) => {
  switch (risk) {
    case "low":
      return <Badge variant="outline" className="bg-success/10 text-success border-success/20">Low Risk</Badge>;
    case "medium":
      return <Badge variant="outline" className="bg-warning/10 text-warning border-warning/20">Medium Risk</Badge>;
    case "high":
      return <Badge variant="outline" className="bg-destructive/10 text-destructive border-destructive/20">High Risk</Badge>;
    case "not-applicable":
      return <Badge variant="outline" className="bg-muted text-muted-foreground">N/A</Badge>;
    default:
      return null;
  }
};

const getSuitabilityBadge = (suitability: string) => {
  switch (suitability) {
    case "suitable":
      return <Badge variant="outline" className="bg-success/10 text-success border-success/20">Suitable</Badge>;
    case "conditional":
      return <Badge variant="outline" className="bg-warning/10 text-warning border-warning/20">Conditional</Badge>;
    case "not-suitable":
      return <Badge variant="outline" className="bg-destructive/10 text-destructive border-destructive/20">Not Suitable</Badge>;
    default:
      return null;
  }
};

const getReadinessBadge = (readiness: string) => {
  switch (readiness) {
    case "ready":
      return <Badge variant="outline" className="bg-success/10 text-success border-success/20">Ready</Badge>;
    case "pending":
      return <Badge variant="outline" className="bg-warning/10 text-warning border-warning/20">Pending</Badge>;
    case "not-ready":
      return <Badge variant="outline" className="bg-destructive/10 text-destructive border-destructive/20">Not Ready</Badge>;
    default:
      return null;
  }
};

const CompliancePanel = ({ compliance, className }: CompliancePanelProps) => {
  const handleDownload = (docName: string) => {
    // Simulate document download
    const content = `${docName} - Generated by ReSource AI\n\nThis is a placeholder for the actual document.`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${docName.toLowerCase().replace(/\s+/g, "-")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Card className={cn("shadow-[var(--shadow-soft)]", className)}>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="text-base flex items-center gap-2">
            <ClipboardCheck className="h-4 w-4" />
            Compliance & Documentation
          </CardTitle>
          {compliance.isComplianceReady && (
            <Badge className="bg-success/10 text-success border-success/20">
              <CheckCircle2 className="h-3 w-3 mr-1" />
              Compliance-Ready Batch
            </Badge>
          )}
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* AI-Generated Summary */}
        <div className="p-3 bg-muted/50 rounded-lg">
          <p className="text-sm text-muted-foreground">{compliance.summary}</p>
        </div>

        {/* Compliance Flags */}
        <div className="space-y-3">
          <h4 className="text-sm font-medium">Compliance Assessment</h4>
          
          <div className="flex items-center justify-between p-3 border rounded-lg">
            <div className="flex items-center gap-2">
              <Utensils className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm">Food-Grade Risk</span>
            </div>
            {getRiskBadge(compliance.foodGradeRisk)}
          </div>

          <div className="flex items-center justify-between p-3 border rounded-lg">
            <div className="flex items-center gap-2">
              <Factory className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm">Industrial-Grade Suitability</span>
            </div>
            {getSuitabilityBadge(compliance.industrialGradeSuitability)}
          </div>

          <div className="flex items-center justify-between p-3 border rounded-lg">
            <div className="flex items-center gap-2">
              <Globe className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm">Export Compliance</span>
            </div>
            {getReadinessBadge(compliance.exportComplianceReadiness)}
          </div>
        </div>

        <Separator />

        {/* Downloadable Documents */}
        <div className="space-y-3">
          <h4 className="text-sm font-medium">Available Documents</h4>
          
          <div className="space-y-2">
            {compliance.documents.map((doc, idx) => (
              <div 
                key={idx}
                className="flex items-center justify-between p-3 border rounded-lg"
              >
                <div className="flex items-center gap-2">
                  {doc.type === "certificate" ? (
                    <FileCheck className="h-4 w-4 text-muted-foreground" />
                  ) : (
                    <ClipboardCheck className="h-4 w-4 text-muted-foreground" />
                  )}
                  <span className="text-sm">{doc.name}</span>
                </div>
                <Button 
                  variant="outline" 
                  size="sm"
                  onClick={() => handleDownload(doc.name)}
                  disabled={!doc.available}
                >
                  <Download className="h-3 w-3 mr-1" />
                  {doc.available ? "Download" : "Unavailable"}
                </Button>
              </div>
            ))}
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default CompliancePanel;
export type { ComplianceData };
